version: '3'

services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: admin
        volumes:
        #Note that this is for Windows.
            - //C/Work/Dockershared/mysql:/var/lib/mysql   
        networks:
            - default
   
    mittoapi:
        image: mittoapi
        build:
          context: .
          dockerfile: dockerfile
        links:
          - db:db
        ports:
          - 8001:80
        restart: always